const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL || '*', credentials: true, methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/products', require('./routes/products'));
app.use('/api/orders', require('./routes/orders'));
app.use('/api/cart', require('./routes/cart'));
app.use('/api/reviews', require('./routes/reviews'));
app.use('/api/users', require('./routes/users'));
app.get('/', (req, res) => res.json({ status: 'OK', app: 'ShopVault API', version: '1.0.0', timestamp: new Date().toISOString() }));
app.get('/api/health', (req, res) => res.json({ status: 'OK' }));
app.get('/api/seed', async (req, res) => { try { const Product = require('./models/Product'); const User = require('./models/User'); const bcrypt = require('bcryptjs'); await Product.deleteMany({}); await User.deleteMany({}); const salt = await bcrypt.genSalt(10); await User.create([{ name: 'Admin', email: 'admin@shopvault.com', password: await bcrypt.hash('admin123', salt), role: 'admin' }, { name: 'Jane', email: 'jane@example.com', password: await bcrypt.hash('password123', salt), role: 'user' }]); const imgs = [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', public_id: 'p1' }, { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', public_id: 'p2' }, { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', public_id: 'p3' }, { url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400', public_id: 'p4' }, { url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400', public_id: 'p5' }, { url: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400', public_id: 'p6' }, { url: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400', public_id: 'p7' }, { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400', public_id: 'p8' }, { url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400', public_id: 'p9' }, { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', public_id: 'p10' }, { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', public_id: 'p11' }, { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', public_id: 'p12' }]; const ps = []; for (let i = 0; i < 12; i++) { ps.push({ name: 'Product ' + (i+1), slug: 'product-' + (i+1), price: 29.99 + i, category: ['Electronics','Clothing','Books'][i%3], description: 'Description for product ' + (i+1), stock: 100, images: [imgs[i]], isActive: true }); } await Product.insertMany(ps); res.json({ message: 'Seeded 12 products!' }); } catch(e) { res.status(500).json({ error: e.message }); } });
app.use((req, res) => res.status(404).json({ message: 'Route ' + req.originalUrl + ' not found' }));
app.use((err, req, res, next) => { const statusCode = err.statusCode || 500; res.status(statusCode).json({ message: err.message || 'Internal server error' }); });
const PORT = process.env.PORT || 5000;
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/shopvault').then(() => { console.log('MongoDB connected'); app.listen(PORT, () => console.log('ShopVault API running on port ' + PORT)); }).catch(err => { console.error('MongoDB error:', err); process.exit(1); });
module.exports = app;